gpt.py updated
kevinscaria/PolyMATH pull request #34
Opened 2024-06-01 08:22 UTC by shreyas301197

1. gpt.py updated with inference and accuracy calculations
2. inferencing on 4 initial folders :
 folders = [
    "QP_Odisha NTSE Stage 1 2017-18) MAT",
    "QP_Maharashtra NTSE Stage 1 2017-18 MAT",
    "QP_Gujarat NTSE Stage 1 2017-18 MAT",
    "QP_Karnataka NTSE Stage1 (2017-18) MAT"
]

2024-06-01 08:54 UTC, kevinscaria requested changes
General comment: I will refactor it eventually to accommodate it as a general class for all API based calls. 

Other comments are nits, not super necessary. Just ensure the formatting issue is intended before pushing.

2024-06-01 08:54 UTC, kevinscaria commented on datastore/QP_Maharashtra NTSE Stage 1 2017-18 MAT/annotations.csv
> +ce48ecfa-9052-5cca-accd-6cbe128e3571,q18,4,['q18_0_c4.png'],,['c4.png'],,,3,4-Jan,
Is the conversion from `1-4` to `4-Jan` intended? Looks like formatting by Excel.

2024-06-01 08:54 UTC, kevinscaria commented on scripts/model inference scripts/gpt.py
> +    def gen_template(self,
nit: better to rename it to more expressive names.

2024-06-01 08:54 UTC, kevinscaria commented on scripts/model inference scripts/gpt.py
> +                     model = "gpt-4-vision-preview",
can't we reference this using the instance field `self.model`?

2024-06-01 08:54 UTC, kevinscaria commented on scripts/model inference scripts/gpt.py
> +            ans = literal_eval(ans)
Are yo sure this literal_eval would work with the addition of `ans += '"}'`

2024-06-01 08:54 UTC, kevinscaria commented on scripts/model inference scripts/gpt.py
> +    def __call__(self):
Just a doubt: Any reason why we have the dunder `__call__` method?

2024-06-02 04:14 UTC, shreyas301197 commented on datastore/QP_Maharashtra NTSE Stage 1 2017-18 MAT/annotations.csv
> +ce48ecfa-9052-5cca-accd-6cbe128e3571,q18,4,['q18_0_c4.png'],,['c4.png'],,,3,4-Jan,
discussed this with Ujjwala, not super important but would eventually be fixed in the annotations code

2024-06-02 04:15 UTC, shreyas301197 commented on scripts/model inference scripts/gpt.py
> +                     model = "gpt-4-vision-preview",
fixed

2024-06-02 04:16 UTC, shreyas301197 commented on scripts/model inference scripts/gpt.py
> +            ans = literal_eval(ans)
yes this is needed in edge cases when the response exceeds token limit.

2024-06-02 04:57 UTC, closed without merging